### ISSUE TITLE
Make stable

### ISSUE THREAD

**Issue by viktorsec** [jxom/hyper-touchbar#3]
Hi,

Hyper now [depends on Electron 1.7.6](https://github.com/zeit/hyper/blob/master/package.json), so it can handle Touch Bar in vanilla.

I just added your plugin to the config and it started working instantly. The README needs an update.

**Comment by jxom** [comment]
I've noticed! However I haven't tested it again ever since, haha. I'll update the readme when I get home.

**Comment by viktorsec** [comment]
My celebrations were preliminary, the buttons render alright, but I'm getting exceptions after pressing them. Still, I assume this is fixable.

```
Uncaught Exception:
TypeError: Cannot read property 'write' of undefined
    at Object.click (~/.hyper_plugins/node_modules/hyper-touchbar/index.js:44:37)
    at TouchBarButton.onInteraction (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/touch-bar.js:169:16)
    at BrowserWindow.interactionListener (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/touch-bar.js:109:14)
    at emitThree (events.js:116:13)
    at BrowserWindow.emit (events.js:197:7)
```

**Comment by jxom** [comment]
Hey @viktorsec - I can't seem to reproduce... It works fine for me. Does it work okay for you now by any chance?

**Comment by alanshortis** [comment]
I just ran into this error - restarting Hyper was all it took to solve it.
